import {
  AdminCard,
  AdminShell,
} from "@/components/admin/admin-shell";
import { requireAdminPage } from "@/lib/admin-auth";

export default async function AnalyticsPrivacyPage() {
  const admin = await requireAdminPage();

  return (
    <AdminShell
      username={admin.username}
      title="Analytics privacy boundary"
      subtitle="Exactly what the Ecommerce Analytics layer stores—and what it is deliberately prevented from becoming."
    >
      <div className="grid gap-5 md:grid-cols-2">
        <AdminCard>
          <p className="text-sm font-semibold">Stored</p>
          <div className="mt-4 grid gap-2 text-sm leading-6 text-black/58">
            <p>Anonymous hashed visitor and session identifiers generated by the website.</p>
            <p>Public page path without URL query strings.</p>
            <p>Coarse device class: mobile, tablet or desktop.</p>
            <p>Sanitized UTM source, medium and campaign labels.</p>
            <p>External referrer domain only—not full referring URLs.</p>
            <p>Product, collection and campaign identifiers.</p>
            <p>Sanitized storefront search phrases with PII-like patterns rejected.</p>
            <p>CRM-confirmed order total, item IDs/quantities and delivery zone for aggregate conversion reporting.</p>
          </div>
        </AdminCard>

        <AdminCard>
          <p className="text-sm font-semibold">Never stored here</p>
          <div className="mt-4 grid gap-2 text-sm leading-6 text-black/58">
            <p>Customer name, email, mobile number or delivery address.</p>
            <p>Order number or CRM customer/order IDs.</p>
            <p>IP address or raw browser user-agent.</p>
            <p>Checkout notes, landmark, support messages or arbitrary free text.</p>
            <p>Payment credentials or financial-account details.</p>
            <p>CRM cost, COGS, supplier, batch or internal finance information.</p>
          </div>
        </AdminCard>
      </div>

      <AdminCard className="mt-5">
        <p className="text-sm font-semibold">Enforced controls</p>
        <div className="mt-4 grid gap-3 text-sm leading-6 text-black/58">
          <p>Browser Do Not Track is respected automatically.</p>
          <p>Customers can disable first-party analytics from the existing privacy preference.</p>
          <p>Client-side order-created events are rejected; revenue is recorded only after CRM confirms the order.</p>
          <p>Confirmed conversions use a one-way hash of the order number only for deduplication.</p>
          <p>Analytics cannot write price, stock, finance or order status.</p>
        </div>
      </AdminCard>
    </AdminShell>
  );
}
